name: Running GitHub Labeler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  label_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@f8d36db286402ecb67054c6a14ec17ba2cd681a0 # tag=v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
